using Application.DTOs;
using Application.Interfaces;
using Application.Services;
using Domain.Entities;
using Microsoft.AspNetCore.Identity;
using Moq;
using System.Threading.Tasks;
using Xunit;

namespace Application.Tests
{
    public class UserManagementServiceTests
    {
        private readonly Mock<UserManager<ApplicationUser>> _userManagerMock;
        private readonly Mock<RoleManager<IdentityRole>> _roleManagerMock;
        private readonly Mock<IAuditoriaService> _auditoriaMock;
        private readonly UserManagementService _service;

        public UserManagementServiceTests()
        {
            var userStore = new Mock<IUserStore<ApplicationUser>>();
            _userManagerMock = new Mock<UserManager<ApplicationUser>>(
                userStore.Object, null!, null!, null!, null!, null!, null!, null!, null!);

            var roleStore = new Mock<IRoleStore<IdentityRole>>();
            _roleManagerMock = new Mock<RoleManager<IdentityRole>>(
                roleStore.Object, null!, null!, null!, null!);

            _auditoriaMock = new Mock<IAuditoriaService>();

            _service = new UserManagementService(
                _userManagerMock.Object,
                _roleManagerMock.Object,
                _auditoriaMock.Object);
        }

        [Fact]
        public async Task ResetPasswordAsync_ShouldSucceed_WithAutoGeneratedPassword()
        {
            // Arrange
            var user = new ApplicationUser
            {
                Id = "user-123",
                UserName = "testuser",
                NombreCompleto = "Test User",
                Activo = true,
                DebeCambiarPassword = false
            };

            _userManagerMock.Setup(m => m.FindByIdAsync("user-123"))
                .ReturnsAsync(user);

            _userManagerMock.Setup(m => m.GeneratePasswordResetTokenAsync(user))
                .ReturnsAsync("dummy-token");

            _userManagerMock.Setup(m => m.ResetPasswordAsync(user, "dummy-token", It.IsAny<string>()))
                .ReturnsAsync(IdentityResult.Success);

            _userManagerMock.Setup(m => m.IsLockedOutAsync(user))
                .ReturnsAsync(false);

            _userManagerMock.Setup(m => m.UpdateAsync(user))
                .ReturnsAsync(IdentityResult.Success);

            var request = new ResetUserPasswordAdminDto
            {
                AutoGenerate = true
            };

            // Act
            var result = await _service.ResetPasswordAsync("user-123", request, "admin");

            // Assert
            Assert.True(result.Success);
            Assert.NotNull(result.Data);
            Assert.Equal("user-123", result.Data.UserId);
            Assert.Equal("testuser", result.Data.Username);
            Assert.True(result.Data.DebeCambiarPassword);
            Assert.False(string.IsNullOrWhiteSpace(result.Data.TemporaryPassword));
            Assert.StartsWith("Udit", result.Data.TemporaryPassword);
            Assert.True(user.DebeCambiarPassword);

            _auditoriaMock.Verify(a => a.LogAsync("EDITAR", "Usuarios", It.Is<string>(s => s.Contains("testuser")), null), Times.Once);
        }

        [Fact]
        public async Task ResetPasswordAsync_ShouldFail_WhenUserNotFound()
        {
            // Arrange
            _userManagerMock.Setup(m => m.FindByIdAsync("invalid-id"))
                .ReturnsAsync((ApplicationUser?)null);

            var request = new ResetUserPasswordAdminDto { AutoGenerate = true };

            // Act
            var result = await _service.ResetPasswordAsync("invalid-id", request, "admin");

            // Assert
            Assert.False(result.Success);
            Assert.Equal("Usuario no encontrado.", result.Message);
        }

        [Fact]
        public async Task ResetPasswordAsync_ShouldSucceed_WithCustomPassword()
        {
            // Arrange
            var user = new ApplicationUser
            {
                Id = "user-456",
                UserName = "customuser",
                Activo = true,
                DebeCambiarPassword = false
            };

            _userManagerMock.Setup(m => m.FindByIdAsync("user-456"))
                .ReturnsAsync(user);

            _userManagerMock.Setup(m => m.GeneratePasswordResetTokenAsync(user))
                .ReturnsAsync("token-456");

            _userManagerMock.Setup(m => m.ResetPasswordAsync(user, "token-456", "CustomPass123!"))
                .ReturnsAsync(IdentityResult.Success);

            _userManagerMock.Setup(m => m.IsLockedOutAsync(user))
                .ReturnsAsync(false);

            _userManagerMock.Setup(m => m.UpdateAsync(user))
                .ReturnsAsync(IdentityResult.Success);

            var request = new ResetUserPasswordAdminDto
            {
                AutoGenerate = false,
                NewTemporaryPassword = "CustomPass123!"
            };

            // Act
            var result = await _service.ResetPasswordAsync("user-456", request, "admin");

            // Assert
            Assert.True(result.Success);
            Assert.NotNull(result.Data);
            Assert.Equal("CustomPass123!", result.Data.TemporaryPassword);
            Assert.True(user.DebeCambiarPassword);
        }
    }
}
